apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  namespace: easytravel
spec:
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
  selector:
    app: backend
  type: ClusterIP
